# Mảng 1 chiều trong 'numpy'

In [2]:
import numpy as np

## 1. Khởi tạo mảng ndarray

### a) Dùng np.array

In [2]:
# Khởi tạo từ list, thay đổi kiểu dữ liệu
### Kiểu dữ liệu mặc định theo giá trị
my_list = [1,2,3,4,5,6] # (số nguyên)
arr_int = np.array(my_list)
print(arr_int)

### Kiểu dữ liệu tự định nghĩa
## Cách 1:
arr_cplx_1 = np.array(my_list, dtype = np.complex_) # (số phức của np)
print(arr_cplx_1)

arr_flt_1 = np.array(my_list, dtype = np.float32) # (số thực 4 byte của np)
print(arr_flt_1)

## Cách 2:
arr_cplx_2 = np.array(my_list, dtype = complex) # (số phức của python)
print(arr_cplx_2)

arr_flt_2 = np.array(my_list, dtype = float) # (số thực của python)
print(arr_flt_2)

[1 2 3 4 5 6]
[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j]
[1. 2. 3. 4. 5. 6.]
[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j]
[1. 2. 3. 4. 5. 6.]


In [3]:
# Khởi tạo từ list, thay đổi số chiều
arr_2D = np.array(my_list, ndmin = 2)
print(arr_2D)

[[1 2 3 4 5 6]]


In [4]:
# Khởi tạo từ tuple
my_tuple = (1,5,0,3)
arr_tuple = np.array(my_tuple)
print(arr_tuple)

[1 5 0 3]


### **Gán nhãn và kiểu dữ liệu tự định nghĩa cho array bằng dtype*

In [5]:
# Gán nhãn và kiểu dữ liệu tự định nghĩa cho array -> dùng dtype
## --- Nhãn 1 thành phần ---
### Tạo dtype có nhãn là 'name', kiểu string 10 ký tự (U10)
dt_1 = np.dtype([('name','U10')])

### Gán dt cho array
arr_name = np.array([('Jack',),('Ken',),('Dan',)], dtype = dt_1)
print(arr_name)
print(arr_name['name']) # Truy xuất theo nhãn

## --- Nhãn 2 thành phần ---
### Tạo dtype có nhãn là 'name', kiểu string 10 ký tự (S10) và nhãn 'age', kiểu số nguyên 1 byte (np.int8 hoặc 'i1')
# dt_2 = np.dtype([('name','U10'), ('age',np.int8)])
dt_2 = np.dtype([('name','U10'), ('age','i1')])

### Gán dt cho array
arr_name_age = np.array([('Jack',21),('Ken',23),('Dan',20)], dtype = dt_2)
print(arr_name_age)
print(arr_name_age['age']) # Truy xuất theo nhãn

[('Jack',) ('Ken',) ('Dan',)]
['Jack' 'Ken' 'Dan']
[('Jack', 21) ('Ken', 23) ('Dan', 20)]
[21 23 20]


### b) Dùng np.asarray

In [6]:
# Khởi tạo dùng np.asarray
arr_asarray = np.asarray([3,4,2])
arr_asarray.sort()
print(arr_asarray)

[2 3 4]


### c) Dùng np.zeros / np.ones

In [7]:
# Khởi tạo 1 mảng gồm n phần tử = 0 -> dùng np.zeros(n)
arr_zeros = np.zeros(10)
print(arr_zeros)

# Khởi tạo 1 mảng gồm n phần tử = 1 -> dùng np.ones(n)
arr_ones = np.ones(5)
print(arr_ones)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


### d) Dùng np.arange

In [8]:
# Khởi tạo dùng np.arange(start,stop,step,dtype)
## Các số chẵn từ 10 tới 18 (ko chạm tới stop)
arr_arange_1 = np.arange(10, 20, 2, dtype = np.int8)
print(arr_arange_1)

## Các số nguyên từ 0 -> 10
arr_arange_2 = np.arange(10)
print(arr_arange_2)

[10 12 14 16 18]
[0 1 2 3 4 5 6 7 8 9]


### e) Dùng np.linspace

In [9]:
# Khởi tạo dùng np.linspace(start,stop,num,endpoint,dtype) 
### Mặc định: num = 50, endpoint = True (lấy cả giá trị step), dtype: float

## Lấy 20 số từ 10 tới 50 (endpoint = False => ko chạm tới stop)
arr_linspace_1 = np.linspace(10, 50, 20, endpoint = False, dtype = np.int8)
print(arr_linspace_1)

## Các số thực từ 10 -> 20 (mặc định dtype là float, num = 50)
arr_linspace_2 = np.linspace(10, 20)
print(arr_linspace_2)
print(arr_linspace_2.dtype)

## Lấy các số nguyên từ 10 -> 200 (num = 50) (cách đều)
arr_linspace_3 = np.linspace(1, 51, endpoint = False, dtype = np.int16)
print(arr_linspace_3)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
[10.         10.20408163 10.40816327 10.6122449  10.81632653 11.02040816
 11.2244898  11.42857143 11.63265306 11.83673469 12.04081633 12.24489796
 12.44897959 12.65306122 12.85714286 13.06122449 13.26530612 13.46938776
 13.67346939 13.87755102 14.08163265 14.28571429 14.48979592 14.69387755
 14.89795918 15.10204082 15.30612245 15.51020408 15.71428571 15.91836735
 16.12244898 16.32653061 16.53061224 16.73469388 16.93877551 17.14285714
 17.34693878 17.55102041 17.75510204 17.95918367 18.16326531 18.36734694
 18.57142857 18.7755102  18.97959184 19.18367347 19.3877551  19.59183673
 19.79591837 20.        ]
float64
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


### f) Dùng np.empty

In [10]:
# Khởi tạo mảng gồm những giá trị ngẫu nhiên -> dùng np.empty(kích thước)
arr_empty = np.empty(5, dtype = int) # khởi tạo mảng 5 phần tử ngẫu nhiên 
print(arr_empty)

[0 0 0 0 0]


### g) Dùng np.empty_like

In [11]:
# Khởi tạo mảng có các thành phần tương tự như trong 1 mảng cho trước (giá trị đc lấy ngẫu nhiên)
# -> dùng np.empty_like(mảng làm mẫu)
arr_prototype_int = ([1,3,6],[4,3,8]) # mảng làm mẫu là mảng số nguyên 2 chiều 2x3
arr_empty_like_int = np.empty_like(arr_prototype_int) # -> mảng mới cũng là mảng số nguyên 2 chiều 2x3 (giá trị lấy ngẫu nhiên)
print(arr_empty_like_int)


arr_prototype_float = ([5.6, 7.2, 6.0]) # mảng làm mẫu là mảng số thực 1 chiều 3 phần tử
arr_empty_like_float = np.empty_like(arr_prototype_float) # -> mảng mới cũng là mảng số thực 1 chiều 3 phần tử (giá trị lấy ngẫu nhiên)
print(arr_empty_like_float)

[[1065353216 1073741824 1077936128]
 [1082130432 1084227584 1086324736]]
[0.00000000e+000 0.00000000e+000 1.21411546e-311]


### h) Dùng np.full

In [12]:
# Khởi tạo mảng gồm những phần tử giống nhau 
# -> dùng np.full(kích_thước, fill_value, dtype)

arr_fill = np.full(5, 100) # khởi tạo mảng 5 phần tử có giá trị 100
print(arr_fill)

[100 100 100 100 100]


## 2. Tìm kích thước mảng

In [13]:
# Kích thước mảng 1 chiều -> dùng shape
print(arr_int)
print(arr_int.shape) # => trả về tuple (số dòng, số cột)
## --> Lấy số phần tử của mảng 1 chiều: arr.shape[0]
print('Mảng có', arr_int.shape[0], 'phần tử')

[1 2 3 4 5 6]
(6,)
Mảng có 6 phần tử


## 3. Cập nhật giá trị của phần tử trong mảng

In [28]:
# Cập nhật giá trị phần tử trong mảng
arr_int[4] = 100
print(arr_int)

[  1   2   3   4 100   6]


## 4. Truy xuất phần tử trong mảng

In [15]:
# Truy xuất phần tử
my_arr = np.arange(20)

## Tại 1 vị trí index = 2
print(my_arr[2])

## Từ vị trí index = 2 đến hết mảng
print(my_arr[2:])

## Từ vị trí index = 2 đến vị trí index = 6
print(my_arr[2:6])

## Truy xuất theo điều kiện: 
### Lấy những phần tử < 9 trong mảng
arr_1 = my_arr[my_arr < 9]
print(arr_1)

### Lấy những phần tử thỏa: 2 <= phần tử <= 9 trong mảng
dieu_kien = (my_arr >= 2) & (my_arr <= 9)
arr_2 = my_arr[dieu_kien]
print(arr_2)

2
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[2 3 4 5]
[0 1 2 3 4 5 6 7 8]
[2 3 4 5 6 7 8 9]


In [16]:
# Truy xuất phần tử -> dùng slice(start,stop,step)
index_slice = slice(3,10,2) # -> 3, 5, 7, 9 ==> Lấy các phần tử ở vị trí 3,5,7,9 trong mảng
print(my_arr)
print(my_arr[index_slice]) # ==> Mảng các phần tử ở vị trí 3,5,7,9 trong mảng
print(my_arr[index_slice][3]) # truy xuất như mảng

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[3 5 7 9]
9


## 5. Thêm/ Chèn phần tử vào mảng

In [17]:
# Thêm phần tử
### Thêm phần tử vào cuối mảng -> dùng np.append(arr, p.tử) (phần tử có thể là 1 giá trị hoặc 1 mảng)
arr_to_append = np.array([100,101,102])
my_arr = np.append(my_arr,arr_to_append)
my_arr = np.append(my_arr,500)
print(my_arr)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19 100 101 102 500]


In [18]:
# Chèn phần tử
### Chèn phần tử vào 1 vị trí index -> dùng np.insert(arr, index, p.tử) (phần tử có thể là 1 giá trị hoặc 1 mảng)
my_arr = np.insert(my_arr, 1, [20,21,22]) # --> Chèn mảng vào vị trí index là 1
my_arr = np.insert(my_arr, 5, 300) # --> Chèn phần tử vào vị trí index là 5
print(my_arr)

[  0  20  21  22   1 300   2   3   4   5   6   7   8   9  10  11  12  13
  14  15  16  17  18  19 100 101 102 500]


## 6. Xóa phần tử trong mảng

In [19]:
# Xóa phần tử tại vị trí index = 2 trong mảng -> dùng np.delete(arr, index)
my_arr_delete = np.delete(my_arr, 2)
print(my_arr_delete)
print(my_arr)

[  0  20  22   1 300   2   3   4   5   6   7   8   9  10  11  12  13  14
  15  16  17  18  19 100 101 102 500]
[  0  20  21  22   1 300   2   3   4   5   6   7   8   9  10  11  12  13
  14  15  16  17  18  19 100 101 102 500]


## 7. Tính toán số học trên mảng

In [20]:
# Tính toán giữa 2 mảng
a = np.arange(5)
b = np.arange(5,10,1)

tong = a + b
hieu = a - b
tich = a * b
thuong = a / b

print(tong, hieu, tich, thuong, sep = '\n')

# Tính toán giữa 1 mảng và 1 số
a_cong = a + 30
a_tru = a - 20
a_nhan = a * 40
a_chia = a / 10

print(a_cong, a_tru, a_nhan, a_chia, sep = '\n')

[ 5  7  9 11 13]
[-5 -5 -5 -5 -5]
[ 0  6 14 24 36]
[0.         0.16666667 0.28571429 0.375      0.44444444]
[30 31 32 33 34]
[-20 -19 -18 -17 -16]
[  0  40  80 120 160]
[0.  0.1 0.2 0.3 0.4]


## 8. Tính toán thống kê trên mảng

### a) Tìm min, max

In [21]:
# Tìm min, max -> dùng np.amax(arr), np.amin(arr)
print(np.amin(my_arr))
print(np.amax(my_arr))

0
500


### b) Tìm trung bình cộng (mean)

In [22]:
# Tìm trung bình cộng -> dùng np.mean(arr)
print(np.mean(my_arr))

48.42857142857143


### c) Tìm trung bình giữa (trung vị)
*(Tự động sắp xếp tăng dần)*<br>
Đối với mảng có số phần tử chẵn -> median là trung bình cộng 2 phần tử ở giữa mảng<br>
VD: a = [1,2,3,4] -> median là trung bình cộng của 2, 3 = (2+3)/2 = 2.5

Đối với mảng có số phần tử lẻ -> median là phần tử ở chính giữa mảng<br>
VD: a = [1,2,3,4,5] -> median là 3 

In [23]:
# Tìm trung bình giữa (trung vị)
a = np.array([1,2,3,4]) 
print(np.median(a))

a = np.array([1,2,3,4,5]) 
print(np.median(a))

2.5
3.0


## 9. Sắp xếp mảng

In [8]:
# Sắp xếp tăng dần -> dùng np.sort(arr)
c = np.array([4,2,5,7,9,0,18,42,1])
c = np.sort(c)
print(c)

# Sắp xếp giảm dần -> sắp xếp tăng dần trước và dùng phép đảo chiều arr[::-1]
c = np.array([4,2,5,7,9,0,18,42,1])
c = np.sort(c)
c = c[::-1]
print(c)

# Sắp xếp mảng tăng dần theo nhãn -> thêm thuộc tính 'order = tên_nhãn'
dt = np.dtype([('name','U10'), ('age','i1')])
arr_BTS = np.array([('Jin',27),('RM',25),('Suga',26),('J-Hope',25),('Jimin',24),('Jungkook',22),('V',24)], dtype = dt)
print(arr_BTS)
print(np.sort(arr_BTS, order='name')) # Sort tăng dần theo tên (thứ tự bảng chữ cái)
print(np.sort(arr_BTS, order='age')) # Sort tăng dần theo tuổi

# Sắp xếp mảng giảm dần theo nhãn -> sắp xếp tăng dần trước và dùng phép đảo chiều arr[::-1]
arr_BTS_name = np.sort(arr_BTS, order='name')
print(arr_BTS_name[::-1])
arr_BTS_age = np.sort(arr_BTS, order='age')
print(arr_BTS_age[::-1])

[ 0  1  2  4  5  7  9 18 42]
[42 18  9  7  5  4  2  1  0]
[('Jin', 27) ('RM', 25) ('Suga', 26) ('J-Hope', 25) ('Jimin', 24)
 ('Jungkook', 22) ('V', 24)]
[('J-Hope', 25) ('Jimin', 24) ('Jin', 27) ('Jungkook', 22) ('RM', 25)
 ('Suga', 26) ('V', 24)]
[('Jungkook', 22) ('Jimin', 24) ('V', 24) ('J-Hope', 25) ('RM', 25)
 ('Suga', 26) ('Jin', 27)]
[('V', 24) ('Suga', 26) ('RM', 25) ('Jungkook', 22) ('Jin', 27)
 ('Jimin', 24) ('J-Hope', 25)]
[('Jin', 27) ('Suga', 26) ('RM', 25) ('J-Hope', 25) ('V', 24)
 ('Jimin', 24) ('Jungkook', 22)]


## 10. Tìm vị trí của các phần tử thỏa điều kiện

In [25]:
d = np.array([2,4,5,8,44,6,3,14,22,11])

# Tìm vị trí những phần tử chẵn lớn hơn 10 trong mảng d
# -> dùng np.where(điều_kiện)
dieu_kien_1 = ((d % 2 == 0) & (d > 10))
indexes = np.where(dieu_kien_1)
print(indexes)
print(d[indexes]) # Đưa index vào để lấy ra giá trị

(array([4, 7, 8], dtype=int64),)
[44 14 22]


## 11. Lấy ra các phần tử thỏa điều kiện

In [26]:
d = np.array([2,4,5,8,44,6,3,14,22,11])

# Rút trích những phần tử chẵn lớn hơn 10 trong mảng d
# -> dùng np.extract(điều_kiện, arr)
d_1 = np.extract(dieu_kien_1, d)
print(d_1)

[44 14 22]


## 12. Kiểm tra trong mảng có giá trị NaN không

In [6]:
e = np.array([2,4,np.NaN,np.NaN,22,11,np.NaN])
f = np.array([2,4,5,8,44,6])
g = np.array([np.NaN,np.NaN,np.NaN,np.NaN])

# Trả về 1 mảng tương đương với mảng cần kiểm tra, nhưng giá trị nào là NaN thì trở thành True, ngược lại là False 
# -> dùng hàm np.isnan(arr)
print(np.isnan(e))

# Trả về True nếu có ít nhất 1 giá trị NaN trong mảng, ngược lại trả vè False
# -> dùng np.isnan(arr).any()
print(np.isnan(e).any())
print(np.isnan(f).any())

# Trả về True nếu tất cả đều là NaN, ngược lại trả vè False
# -> dùng np.isnan(arr).all()
print(np.isnan(e).all())
print(np.isnan(f).all())
print(np.isnan(g).all())

[False False  True  True False False  True]
True
False
False
False
True


## 13. Thay các giá trị NaN bằng 0

In [8]:
e = np.array([2,4,np.NaN,np.NaN,22,11,np.NaN])
e[np.isnan(e)] = 0
print(e)

[ 2.  4.  0.  0. 22. 11.  0.]
