In [1]:
import numpy as np

# Câu 1: 
# a. Tạo numpy array có giá trị từ 0-9
arr1 = np.arange(0,10)
print(arr1)

# b. Kiểu dữ liệu (type) của arr1 => numpy.ndarray
print(type(arr1))

# c. Kích thước (shape) của arr1
print(arr1.shape)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(10,)


In [2]:
# Câu 2: 
# a. Tạo numpy array gồm những phần tử chẵn từ arr1
arr_even = arr1[arr1 % 2 == 0]
print(arr_even)

# b. Tạo numpy array gồm những phần tử lẻ từ arr1
arr_even = arr1[arr1 % 2 != 0]
print(arr_even)

print(arr1)

[0 2 4 6 8]
[1 3 5 7 9]
[0 1 2 3 4 5 6 7 8 9]


In [3]:
# Câu 3: Tạo numpy array mà những phần tử lẻ đổi thành 100
arr_update_1 = np.array(arr1) # Copy arr1 qua arr_update_1
# (ko dùng arr_update_1 = arr1 vì mảng là con trỏ)

arr_update_1[arr_update_1 % 2 != 0] = 100 # Gán các phần tử lẻ = 100
print(arr_update_1)

[  0 100   2 100   4 100   6 100   8 100]


In [4]:
# Câu 4: Lấy phần chung (phần giao) của 2 array => Hàm np.intersect1d
print(arr_update_1)
arr_intersect = np.intersect1d(arr1, arr_update_1)
print(arr_intersect)

[  0 100   2 100   4 100   6 100   8 100]
[0 2 4 6 8]


In [5]:
# Câu 5: Lấy các phần tử chỉ thuộc arr1 mà không thuộc arr_update_1 => Hàm np.setdiff1d
print(arr_update_1)
arr_setdiff = np.setdiff1d(arr1, arr_update_1)
print(arr_setdiff)

[  0 100   2 100   4 100   6 100   8 100]
[1 3 5 7 9]


In [13]:
# Câu 6: 
## Cho array e:
e = np.arange(20)

## Tạo array f chỉ chứa các phần tử có giá trị từ 5-10 của e:
# Cách 1:
f = e[(e >= 5) & (e <= 10)]
print(f)

# Cách 2:
f = np.extract(((e >= 5) & (e <= 10)), e)
print(f)

[ 5  6  7  8  9 10]
[ 5  6  7  8  9 10]


In [16]:
# Câu 7: Tạo array có 10 phần tử 0
arr_0 = np.zeros(10, dtype = int)
print(arr_0)

# Cập nhật phần tử ở vị trí thứ 5 thành 1
arr_0[5] = 1
print(arr_0)

[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0]


In [33]:
# Câu 8: 
## Tạo array 12 phần tử có giá trị ngẫu nhiên từ 10 -> 24
arr_8 = np.array(np.random.randint(10, 25, 12))
print(arr_8)

## Sắp xếp giảm dần
#### Sắp tăng dần trước:
arr_8 = np.sort(arr_8)
print('Ascending:', arr_8)

#### Đảo ngược lại để thành giảm dần
arr_8_reverse = arr_8[::-1]
print('Descending: ', arr_8_reverse)

[11 21 12 23 20 22 19 14 23 14 24 19]
Ascending: [11 12 14 14 19 19 20 21 22 23 23 24]
Descending:  [24 23 23 22 21 20 19 19 14 14 12 11]


In [35]:
# Câu 9: 
## Khởi tạo 1 array k gồm 10 phần tử ngẫu nhiên từ 1 -> 30
k = np.array([0,5,2,3,0,4,8,9,1,10,0])
print(k)

## Tạo array L từ k với các phần tử đều khác 0
#Cách 1:
L = k[k != 0]
print(L)

#Cách 2: dùng hàm nonzero => trả về index các phần tử khác 0
zero_indexes = k.nonzero()
L = k[zero_indexes]
print(L)

[ 0  5  2  3  0  4  8  9  1 10  0]
[ 5  2  3  4  8  9  1 10]
[ 5  2  3  4  8  9  1 10]


In [37]:
# Câu 10: Thêm 2 phần tử 10, 20 vào cuối mảng L
L = np.append(L, [10, 20])
print(L)

[ 5  2  3  4  8  9  1 10 10 20]


In [38]:
# Câu 12: Xóa phần tử index = 0, 1, 2
L = np.delete(L, [0,1,2])
print(L)

[ 4  8  9  1 10 10 20]
