In [2]:
import numpy as np

# Khởi tạo mảng bằng arange
a = np.arange(20)
b = np.arange(10, 30, 5)

In [14]:
import random
# Khởi tạo list 20 phần tử có giá trị ngẫu nhiên từ 10 tới 30
lst = [random.randint(10, 30) for i in range(20)]
print(lst)

# Chuyển sang ndarray
c = np.array(lst)
print(c)

[26, 13, 29, 21, 21, 18, 22, 13, 15, 27, 10, 20, 17, 11, 23, 14, 21, 19, 25, 17]
[26 13 29 21 21 18 22 13 15 27 10 20 17 11 23 14 21 19 25 17]


In [22]:
# Tìm max, min
print(np.amax(c))
print(np.amin(c))
print(np.mean(c))
mc = np.median(c)
print(mc)

29
10
19.1
19.5


In [17]:
# Khởi tạo mảng ndarray 3 phần tử ngẫu nhiên 
# trong khoảng từ 10 -> 30 bằng np.random.randint
lst1 = np.random.randint(10, 30, 3)
d = np.array(lst1)
print(d)

[23 10 27]


In [5]:
# Sort tăng dần
a = np.sort(a)
print(a)

# Sort giảm dần
a = a[::-1]
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [9]:
# Where (tìm index của các phần tử thỏa điều kiện)
index = np.where(a < 10)
print(index)
print(a[index]) # Phan tu tai index do

(array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19], dtype=int64),)
[9 8 7 6 5 4 3 2 1 0]


In [10]:
# Extract (tìm các phần tử thỏa điều kiện)
print(np.extract(a > 15, a))

[19 18 17 16]
