In [2]:
import numpy as np

In [3]:
# khoi tao 1
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)
b = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[8,9,10]]])
print(b)
print(b.shape)
# tim max, min
print(np.amax(a))
print(np.amin(a))
print(np.amax(a,axis=0))
print(np.amax(a,axis=1))

[[1 2 3]
 [4 5 6]]
(2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [ 8  9 10]]]
(2, 2, 3)
6
1
[4 5 6]
[3 6]


In [4]:
# khoi tao 2
c = np.array(np.random.uniform(5,10,[3,5]), dtype='i')
print(c)
print(c.shape)

[[5 9 7 9 9]
 [5 5 7 5 7]
 [8 6 6 7 9]]
(3, 5)


In [5]:
# khoi tao 3
dt = np.dtype([("name","S10"),("age","i8"),("point","float16")])
d = np.array([("Tom",50,4.5),("Jane",30,1.6),("Jack",40,2.7)], dtype=dt)
print(d["name"])
print(d["age"])
print(d["point"])
print(d)
# sap tang theo name
print(np.sort(d,order='name'))
# sap tang theo age
print(np.sort(d,order='age'))

[b'Tom' b'Jane' b'Jack']
[50 30 40]
[4.5 1.6 2.7]
[(b'Tom', 50, 4.5) (b'Jane', 30, 1.6) (b'Jack', 40, 2.7)]
[(b'Jack', 40, 2.7) (b'Jane', 30, 1.6) (b'Tom', 50, 4.5)]
[(b'Jane', 30, 1.6) (b'Jack', 40, 2.7) (b'Tom', 50, 4.5)]
