# Mảng nhiều chiều trong 'numpy'

In [1]:
import numpy as np

## 1. Khởi tạo mảng ndarray

### a) Dùng np.array

In [2]:
# Khởi tạo mảng 2 chiều từ list
list_2D = [[1,2,3], [4,5,6]]
arr_2D = np.array(list_2D)
print(arr_2D)

# Khởi tạo mảng 3 chiều từ list
# (mảng 3 chiều chứa các mảng 2 chiều)
list_3D = [[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]]
arr_3D = np.array(list_3D)
print(arr_3D)

[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### b) Dùng np.zeros / np.ones

In [3]:
# Khởi tạo mảng 2 chiều 2x3, các giá trị đều là 0
arr_zeros_2D = np.zeros([2,3])
print(arr_zeros_2D)

# Khởi tạo mảng 3 chiều gồm: 2 ma trận, mỗi ma trận 3x4, các giá trị đều là 1
# (mảng 3 chiều chứa các mảng 2 chiều)
arr_ones_3D = np.ones([2,3,4])
print(arr_ones_3D)

[[0. 0. 0.]
 [0. 0. 0.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


## 2. Tìm kích thước mảng

In [4]:
# Kích thước mảng -> dùng shape
print(arr_3D)
print(arr_3D.shape) # => trả về tuple (số dòng, số cột)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


## 3. Cập nhật giá trị của phần tử trong mảng

In [5]:
# Cập nhật giá trị phần tử trong mảng
arr_3D[0][1][2] = 100
print(arr_3D)

[[[  1   2   3]
  [  4   5 100]]

 [[  7   8   9]
  [ 10  11  12]]]


## 4. Truy xuất phần tử trong mảng

In [6]:
# Truy xuất ma trận index = 1, dòng thứ 0, phần tử từ index = 1 đến hết
print(arr_3D[1][0][1:])

[8 9]


## 5. Thay đổi kích thước (chiều)

In [7]:
# Cách 1: dùng arr.shape = (kích thước mới)
a = np.arange(12) # mảng 2 chiều 1x12
a.shape = (4,3) # -> mảng 2 chiều 4x3
print(a)

# Cách 2: dùng arr.reshape(kích thước mới)
a = np.arange(12) # mảng 2 chiều 1x12
a = a.reshape(2,6) # -> mảng 2 chiều 2x6
print(a)

a = a.reshape(2,3,2) # -> mảng 3 chiều 2 ma trận 3x2
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


## 6. Tạo mảng con

In [8]:
b = np.arange(30).reshape(3,2,5) # -> mảng 3 chiều 3 ma trận 2x5
print('b:\n', b)
print()

# Cú pháp: arr[ma_trận, dòng, cột]

# Lấy ma trận index = 1 đến hết
b_1 = b[1:]
print('b_1:\n', b_1)
print()

# Lấy các cột có index = 2 của b
## lấy tất cả ma trận -> dùng '0:', lấy tất cả các dòng -> dùng '...'
b_cot_2 = b[0:,...,2]
print('b_cot_2:\n', b_cot_2)
print()

# Lấy cột có index = 3 của ma trận index = 1 trong b
## lấy tất cả các dòng -> dùng '...'
b_mt_1_cot_3 = b[1,...,3]
print('b_mt_1_cot_3:\n', b_mt_1_cot_3)
print()

# Lấy các dòng có index = 0 của b
## lấy tất cả ma trận -> dùng '0:', lấy tất cả các cột -> dùng '...'
b_dong_0 = b[0:,0,...]
print('b_dong_0:\n', b_dong_0)
print()

# Lấy dòng có index = 1 của ma trận index = 2 trong b
## lấy tất cả các cột -> dùng '...'
b_mt_2_dong_1 = b[2,1,...]
print('b_mt_2_dong_1:\n', b_mt_2_dong_1)
print()

# Lấy giá trị 16 trong b
## index: ma trận 1, dòng = 1, cột 1
b_16 = b[1,1,1]
print('b_16:\n', b_16)
print()

b:
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]

b_1:
 [[[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]

b_cot_2:
 [[ 2  7]
 [12 17]
 [22 27]]

b_mt_1_cot_3:
 [13 18]

b_dong_0:
 [[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]]

b_mt_2_dong_1:
 [25 26 27 28 29]

b_16:
 16



## 7. Tính toán số học trên mảng

In [9]:
# 2 mảng phải giống số chiều
c = np.arange(30).reshape(2,5,3)
d = np.arange(130,160,1).reshape(2,5,3)

print(c+d)
print(c-d)
print(c*d)
print(c/d)

[[[130 132 134]
  [136 138 140]
  [142 144 146]
  [148 150 152]
  [154 156 158]]

 [[160 162 164]
  [166 168 170]
  [172 174 176]
  [178 180 182]
  [184 186 188]]]
[[[-130 -130 -130]
  [-130 -130 -130]
  [-130 -130 -130]
  [-130 -130 -130]
  [-130 -130 -130]]

 [[-130 -130 -130]
  [-130 -130 -130]
  [-130 -130 -130]
  [-130 -130 -130]
  [-130 -130 -130]]]
[[[   0  131  264]
  [ 399  536  675]
  [ 816  959 1104]
  [1251 1400 1551]
  [1704 1859 2016]]

 [[2175 2336 2499]
  [2664 2831 3000]
  [3171 3344 3519]
  [3696 3875 4056]
  [4239 4424 4611]]]
[[[0.         0.00763359 0.01515152]
  [0.02255639 0.02985075 0.03703704]
  [0.04411765 0.05109489 0.05797101]
  [0.0647482  0.07142857 0.07801418]
  [0.08450704 0.09090909 0.09722222]]

 [[0.10344828 0.10958904 0.11564626]
  [0.12162162 0.12751678 0.13333333]
  [0.13907285 0.14473684 0.1503268 ]
  [0.15584416 0.16129032 0.16666667]
  [0.17197452 0.17721519 0.18238994]]]


## 8. Tính toán thống kê trên mảng

### a) Tìm min, max

In [10]:
e = np.array([[31,22,43,64,5],[16,27,8,59,130],[11,52,23,4,15]])
print(e)

# Tìm min, max trên toàn mảng
print(np.amin(e))
print(np.amax(e))

# Tìm min, max theo dòng trong từng ma trận con (axis = 1)
print('Max theo dòng trong từng ma trận con:\n', np.amax(e, axis=1))
print('Min theo dòng trong từng ma trận con:\n', np.amin(e, axis=1))

# Tìm min, max theo cột trong từng ma trận con (axis = 0)
print('Max theo cột trong từng ma trận con:\n', np.amax(e, axis=0))
print('Min theo cột trong từng ma trận con:\n', np.amin(e, axis=0))

[[ 31  22  43  64   5]
 [ 16  27   8  59 130]
 [ 11  52  23   4  15]]
4
130
Max theo dòng trong từng ma trận con:
 [ 64 130  52]
Min theo dòng trong từng ma trận con:
 [5 8 4]
Max theo cột trong từng ma trận con:
 [ 31  52  43  64 130]
Min theo cột trong từng ma trận con:
 [11 22  8  4  5]


### b) Tìm trung bình cộng (mean)

In [11]:
# Trên toàn mảng
print(np.mean(e))

# Trên dòng (axis = 1)
print(np.mean(e, axis=1))

# Trên cột (axis = 0)
print(np.mean(e, axis=0))

34.0
[33. 48. 21.]
[19.33333333 33.66666667 24.66666667 42.33333333 50.        ]


### c) Tìm trung bình giữa/trung vị (median)

In [12]:
# Trên toàn mảng
print(np.median(e))

# Trên dòng (axis = 1)
print(np.median(e, axis=1))

# Trên cột (axis = 0)
print(np.median(e, axis=0))

23.0
[31. 27. 15.]
[16. 27. 23. 59. 15.]


### d) Tìm độ lệch chuẩn

In [13]:
# Trên toàn mảng
print(np.std(e))

# Trên dòng (axis = 1)
print(np.std(e, axis=1))

# Trên cột (axis = 0)
print(np.std(e, axis=0))

31.728010758108784
[19.84943324 44.51965858 16.673332  ]
[ 8.49836586 13.12334646 14.33720878 27.18251072 56.71566509]


## 9. Sắp xếp mảng

In [18]:
# Sắp xếp tăng dần -> dùng np.sort(arr)
f = np.array([[13,20,52,14,95],[116,27,80,9,10],[24,2,-31,47,55]])
f = np.sort(f)
# print(f)

# Sắp xếp tăng dần theo dòng (axis = 1)
f = np.array([[13,20,52,14,95],[116,27,80,9,10],[24,2,-31,47,55]])
f = np.sort(f, axis = 1)
print(f)

# Sắp xếp tăng dần theo cột (axis = 0)
f = np.array([[13,20,52,14,95],[116,27,80,9,10],[24,2,-31,47,55]])
f = np.sort(f, axis = 0)
print(f)

# Sắp xếp giảm dần -> dùng dấu '-'
f = np.array([[13,20,52,14,95],[116,27,80,9,10],[24,2,-31,47,55]])
f = -np.sort(-f)
print(f)

# Sắp xếp giảm dần theo dòng (axis = 1)
f = np.array([[13,20,52,14,95],[116,27,80,9,10],[24,2,-31,47,55]])
f = -np.sort(-f, axis = 1)
print(f)

# Sắp xếp giảm dần theo cột (axis = 0)
f = np.array([[13,20,52,14,95],[116,27,80,9,10],[24,2,-31,47,55]])
f = -np.sort(-f, axis = 0)
print(f)

[[ 13  14  20  52  95]
 [  9  10  27  80 116]
 [-31   2  24  47  55]]
[[ 13   2 -31   9  10]
 [ 24  20  52  14  55]
 [116  27  80  47  95]]
[[ 95  52  20  14  13]
 [116  80  27  10   9]
 [ 55  47  24   2 -31]]
[[ 95  52  20  14  13]
 [116  80  27  10   9]
 [ 55  47  24   2 -31]]
[[116  27  80  47  95]
 [ 24  20  52  14  55]
 [ 13   2 -31   9  10]]


## 10. Tìm vị trí của các phần tử thỏa điều kiện

In [26]:
g = np.array([[13,20,52,14,95],[116,27,80,9,10],[24,2,-31,47,55]])

# Tìm vị trí (index) những phần tử chẵn lớn hơn 10 trong mảng g
# -> dùng np.where(điều_kiện)
dieu_kien_1 = (g % 2 == 0) & (g > 10)
indexes = np.where(dieu_kien_1)
print(indexes)
print(g[indexes]) # Đưa index vào để lấy ra giá trị

(array([0, 0, 0, 1, 1, 2], dtype=int64), array([1, 2, 3, 0, 2, 0], dtype=int64))
[ 20  52  14 116  80  24]


## 11. Lấy ra các phần tử thỏa điều kiện

In [29]:
g = np.array([[13,20,52,14,-95],[116,-27,-80,9,10],[24,2,-31,47,55]])

# Rút trích những phần tử lẻ và < 0
# -> dùng np.extract(điều_kiện, arr)
dieu_kien_2 = (g % 2 != 0) & (g < 0)
g_1 = np.extract(dieu_kien_2, g)
print(g_1)

[-95 -27 -31]


## 12. Kiểm tra trong mảng có giá trị NaN không

In [33]:
e = np.array([2,4,np.NaN,np.NaN,22,np.NaN]).reshape(2,3)
f = np.array([2,4,5,8,44,6]).reshape(2,3)
g = np.array([np.NaN,np.NaN,np.NaN,np.NaN,np.NaN,np.NaN]).reshape(2,3)

# Trả về 1 mảng tương đương với mảng cần kiểm tra, nhưng giá trị nào là NaN thì trở thành True, ngược lại là False 
# -> dùng hàm np.isnan(arr)
print(np.isnan(e))

# Trả về True nếu có ít nhất 1 giá trị NaN trong mảng, ngược lại trả vè False
# -> dùng np.isnan(arr).any()
print(np.isnan(e).any())
print(np.isnan(f).any())

# Trả về True nếu tất cả đều là NaN, ngược lại trả vè False
# -> dùng np.isnan(arr).all()
print(np.isnan(e).all())
print(np.isnan(f).all())
print(np.isnan(g).all())

[[False False  True]
 [ True False  True]]
True
False
False
False
True


## 13. Thay các giá trị NaN bằng 0

In [34]:
e = np.array([2,4,np.NaN,np.NaN,22,11,np.NaN])
e[np.isnan(e)] = 0
print(e)

[ 2.  4.  0.  0. 22. 11.  0.]
