In [4]:
## Mảng đa chiều
import numpy as np

# Khởi tạo mảng 2 chiều
data = []
data.append([8,7,9])
data.append([8.5,8,9.5])
data.append([9,8,7.5])
data.append([7.5,10,9])
data.append([8.5,6.5,9.5])
data.append([6,10,8])
print(data)

mang_diem = np.array(data, dtype = float)
print(mang_diem)

[[8, 7, 9], [8.5, 8, 9.5], [9, 8, 7.5], [7.5, 10, 9], [8.5, 6.5, 9.5], [6, 10, 8]]
[[ 8.   7.   9. ]
 [ 8.5  8.   9.5]
 [ 9.   8.   7.5]
 [ 7.5 10.   9. ]
 [ 8.5  6.5  9.5]
 [ 6.  10.   8. ]]


In [10]:
# Tính điểm trung bình
# Cách 1
#print(np.mean(np.array([8,7,9])))
for dong in np.arange(mang_diem.shape[0]):
    dtb = np.mean(mang_diem[dong])
    print('Điểm trung bình của dòng %i là: %.3f' %(dong, dtb))

# Cách 2
print(np.mean(mang_diem, axis = 1))    

Điểm trung bình của dòng 0 là: 8.000
Điểm trung bình của dòng 1 là: 8.667
Điểm trung bình của dòng 2 là: 8.167
Điểm trung bình của dòng 3 là: 8.833
Điểm trung bình của dòng 4 là: 8.167
Điểm trung bình của dòng 5 là: 8.000
[8.         8.66666667 8.16666667 8.83333333 8.16666667 8.        ]


In [11]:
# Tìm max, min theo cột (0), dòng (1)
print(np.amax(data, axis = 0))
print(np.amax(data, axis = 0)[0])
print(np.amin(data, axis = 1))

[ 9.  10.   9.5]
9.0
[7.  8.  7.5 7.5 6.5 6. ]


In [19]:
# Khởi tạo mảng 3 chiều
#Cách 1
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)

#Cách 2
c = np.array(np.random.uniform(5, 10, [3, 5]))
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[7.89745575 9.63285093 6.88618128 7.58314969 7.18895302]
 [5.23896735 5.39273366 6.28367127 6.23655057 8.54020964]
 [6.08164154 6.83967501 5.90845334 6.50786258 8.83876344]]


In [15]:
# Tìm min, max của 1 ma trận con trong mảng 3 chiều
print(np.amin(b[0]))
print(np.amax(b[1]))

1
8
