In [20]:
import numpy as np

# Chép dữ liệu trong file heights_1.txt và weights_1.txt
# vào 2 array height và weight
f_Height = open('DuLieu/heights_1.txt')
data_height = f_Height.read()
f_Height.close()

f_Weight = open('DuLieu/weights_1.txt')
data_weight = f_Weight.read()
f_Weight.close()

# Tách giá trị theo dấu ','
data_height = data_height.split(',')
data_weight = data_weight.split(',')
# print(data_height)
# print(data_weight)

# Chuyển sang kiểu int
data_height = [int(item1) for item1 in data_height]
data_weight = [int(item2) for item2 in data_weight]
# print(data_height)
# print(data_weight)

# Chuyển sang numpy array
data_height = np.array(data_height)
data_weight = np.array(data_weight)
print(data_height)
print(data_weight)

[74 74 72 ... 75 75 73]
[180 215 210 ... 205 190 195]


In [21]:
# Đổi chiều cao từ inch -> m bằng cách nhân với 0.0254
data_height_m = data_height * 0.0254
print(data_height_m)

[1.8796 1.8796 1.8288 ... 1.905  1.905  1.8542]


In [24]:
# Đổi cân nặng từ pound -> kg bằng cách nhân với 0.453592
data_weight_kg = data_weight * 0.453592
print(data_weight_kg)

[81.64656 97.52228 95.25432 ... 92.98636 86.18248 88.45044]


In [25]:
# Tính BMI:
data_bmi = data_weight_kg / (data_height_m ** 2)
print(data_bmi)

[23.11037639 27.60406069 28.48080465 ... 25.62295933 23.74810865
 25.72686361]


In [29]:
# Tìm BMI < 21
print(data_bmi[data_bmi < 21])

[20.54255679 20.54255679 20.69282047 20.69282047 20.34343189 20.34343189
 20.69282047 20.15883472 19.4984471  20.69282047 20.9205219 ]


In [26]:
# weight[50]
print(data_weight_kg[50])

90.7184


In [28]:
# height [100->110] (lấy cả index 110)
print(data_height_m[100:111])

[1.8542 1.8796 1.8288 1.8542 1.7526 1.8288 1.8542 1.905  1.905  1.8542
 1.8288]
