In [4]:
import numpy as np

# Câu 1: Khởi tạo array 3x3 với tất cả giá trị là True => Hàm np.ones
a = np.ones((3,3), dtype = bool)
print(a)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [5]:
# Câu 2:
## Khởi tạo array 1 chiều 0-8
b = np.arange(0, 9)
print(b)

## Chuyển b thành array 3x3
b = b.reshape(3,3)
print(b)
# Hoặc
b.shape = (3,3)
print(b)

## Tạo array mới đảo cột 1 của array b thành cột 3
## => xuất tất cả dòng (:)
## => xuất các cột theo thứ tự: cột 2 -> 1 -> 0
b1 = b[:, [2,1,0]]
print(b1)

# Cách 2: swap
b2 = np.array(b)
temp = np.array(b2[:,0])
b2[:,0] = b2[:,2]
b2[:,2] = temp
print(b2)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [6]:
# Câu 3:
## Tạo array mới đảo dòng 1 của array b thành dòng 2
## => xuất các dòng theo thứ tự: dòng 1 -> 0 -> 2
## => xuất tất cả cột (:)
b3 = b[[1,0,2],:]
print(b3)

[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [7]:
# Câu 4: Đảo ngược dòng của array b
b4 = b[::-1, :]
print(b)
print(b4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [8]:
# Câu 5: Đảo ngược cột của array b
b5 = b[:, ::-1]
print(b)
print(b5)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [9]:
# Câu 6:
h = np.array([[1,2,3],[np.NaN,5,6],[7,np.NaN,9],[4,5,6]])
print(h)

## Kiểm tra h có giá trị rỗng (NaN) nào ko =>  np.isnan(h)
print(np.isnan(h)) # Tạo array chỉ có True/False (True nếu là NaN)
print(np.isnan(h).any()) # Kiểm tra có NaN nào ko (True nêú có tồn tại 1 giá trị NaN)
print(np.isnan(h).all()) # Kiểm tra có phải tất cả đều là NaN ko (True nêú toàn NaN)

[[ 1.  2.  3.]
 [nan  5.  6.]
 [ 7. nan  9.]
 [ 4.  5.  6.]]
[[False False False]
 [ True False False]
 [False  True False]
 [False False False]]
True
False


In [10]:
# Câu 7: Thay thế giá trị NaN bằng 0
h[np.isnan(h)] = 0
print(h)

[[1. 2. 3.]
 [0. 5. 6.]
 [7. 0. 9.]
 [4. 5. 6.]]
