In [1]:
import numpy as np

In [2]:
# khoi tao mang 1 chieu
a = np.array([23,45,67,12,28])
print(a)


[23 45 67 12 28]


In [3]:
print(a.shape)

(5,)


In [4]:
print(a[3])

12


In [5]:
a = np.append(a,[15,10,9])
print(a)

[23 45 67 12 28 15 10  9]


In [6]:
print(type(a))

<class 'numpy.ndarray'>


In [7]:
data = [1,2,3,4,5]
b = np.array(data)
print(b)

[1 2 3 4 5]


In [8]:
a = np.array([23,45,67,12,28], dtype=float)
print(a)


[23. 45. 67. 12. 28.]


In [10]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b.shape)
print(b.shape[0])
print(b.shape[1])

[[1 2 3]
 [4 5 6]]
(2, 3)
2
3


In [11]:
c = np.arange(24)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [15]:
c.shape = (4,6)
print(c)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [16]:
c.shape = (3,2,4)
print(c)


[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


In [17]:
print(c[0])

[[0 1 2 3]
 [4 5 6 7]]


In [18]:
print(c[0,0,3])

3


In [19]:
print(c[0,0])

[0 1 2 3]


In [25]:
dt = np.dtype([('age','i8')])
a = np.array([(25),(34),(21),(40),(26)], dtype=dt)
print(a)
print(type(a))
print(a['age'])
print(a['age'][3])

[(25,) (34,) (21,) (40,) (26,)]
<class 'numpy.ndarray'>
[25 34 21 40 26]
40


In [26]:
# cach 1
name = np.array(['Tom','Jack','Jane','King'])
age = np.array([21,17,23,32])
print('name:',name)
print('age:',age)

name: ['Tom' 'Jack' 'Jane' 'King']
age: [21 17 23 32]


In [27]:
# cach 2
a = np.array([['Tom',21],['Jack',17],['Jane',23],['King',32]])
print(a)
print(a.shape)

[['Tom' '21']
 ['Jack' '17']
 ['Jane' '23']
 ['King' '32']]
(4, 2)


In [32]:
# cach 3
dt = np.dtype([('name','S10'),('age','i1')])
a = np.array([('Tom',21),('Jack',17),('Jane',23),('King',32)], dtype=dt)
print(a)
print(a.shape)
print('name:',a['name'])
print('age:',a['age'])

[(b'Tom', 21) (b'Jack', 17) (b'Jane', 23) (b'King', 32)]
(4,)
name: [b'Tom' b'Jack' b'Jane' b'King']
age: [21 17 23 32]


In [35]:
for i in range(a.shape[0]):
    print('Name:',a['name'][i])
    print('Age:',a['age'][i])
    print('\n')

Name: b'Tom'
Age: 21


Name: b'Jack'
Age: 17


Name: b'Jane'
Age: 23


Name: b'King'
Age: 32




In [37]:
a = np.arange(20)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [39]:
a = np.arange(10,30,5)
print(a)

[10 15 20 25]


In [40]:
a = np.arange(20)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [41]:
print(a[a>10])

[11 12 13 14 15 16 17 18 19]


In [42]:
b = a[a>10]
print(b)

[11 12 13 14 15 16 17 18 19]


In [44]:
s = [a>10]
print(a[tuple(s)])

[11 12 13 14 15 16 17 18 19]


In [45]:
a = np.array
print(a)

<built-in function array>


In [47]:
for i in range(1,101):
    a = np.append(a,i)
print(a)    

[<built-in function array> 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67
 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91
 92 93 94 95 96 97 98 99 100 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18
 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42
 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66
 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90
 91 92 93 94 95 96 97 98 99 100]


In [48]:
a = np.array
a = np.array([1,2,3])
print(a+10)


[11 12 13]
