In [1]:
import numpy as np

In [2]:
# khoi tao mang 1 chieu
a = np.array([23,45,67,12,28])
print(a)


[23 45 67 12 28]


In [3]:
print(a.shape)

(5,)


In [4]:
print(a[3])

12


In [5]:
a = np.append(a,[15,10,9])
print(a)

[23 45 67 12 28 15 10  9]


In [6]:
print(type(a))

<class 'numpy.ndarray'>


In [7]:
data = [1,2,3,4,5]
b = np.array(data)
print(b)

[1 2 3 4 5]


In [8]:
a = np.array([23,45,67,12,28], dtype=float)
print(a)


[23. 45. 67. 12. 28.]


In [10]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b.shape)
print(b.shape[0])
print(b.shape[1])

[[1 2 3]
 [4 5 6]]
(2, 3)
2
3


In [11]:
c = np.arange(24)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [15]:
c.shape = (4,6)
print(c)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [16]:
c.shape = (3,2,4)
print(c)


[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


In [17]:
print(c[0])

[[0 1 2 3]
 [4 5 6 7]]


In [18]:
print(c[0,0,3])

3


In [19]:
print(c[0,0])

[0 1 2 3]
