In [1]:
import numpy as np

In [2]:
# khoi tao 1
a = np.array([20,40,30,45,32])
print(a)
print(a.shape)
print(a.shape[0])
# them
a = np.append(a,[45,60])
print(a)
# chen
a = np.insert(a,1,[25,27])
print(a)
# xoa
a = np.delete(a,[0,1])
print(a)

[20 40 30 45 32]
(5,)
5
[20 40 30 45 32 45 60]
[20 25 27 40 30 45 32 45 60]
[27 40 30 45 32 45 60]


In [3]:
# khoi tao 2
b = np.arange(20)
print(b)
b = np.arange(10,100,5)
print(b)
print(b.shape[0])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
18


In [4]:
# khoi tao 3
import random
lst = [random.randint(20,50) for i in range(20)]
lst = np.random.randint(20,50,20)
c = np.array(lst)
print(c)
print(c.shape[0])
# tim max, min
print(np.amax(c))
print(np.amin(c))
print(np.mean(c))
mc = np.median(c)
print(mc)
# sap xep tang
print(np.sort(c))
# sap xep giam
print(-np.sort(-c))
#
c = np.sort(c)
c = c[::-1]
# rut trich
print(np.extract(c>mc,c))
print(np.sort(np.extract(c>mc,c)))

[42 39 21 34 31 34 22 21 37 26 23 36 29 34 37 21 39 40 45 32]
20
45
21
32.15
34.0
[21 21 21 22 23 26 29 31 32 34 34 34 36 37 37 39 39 40 42 45]
[45 42 40 39 39 37 37 36 34 34 34 32 31 29 26 23 22 21 21 21]
[42 39 37 36 37 39 40 45]
[36 37 37 39 39 40 42 45]


In [5]:
# khoi tao 4
dt = np.dtype([('age','i8')])
d = np.array([10,20,30],dtype=dt)
print(d)
print(type(d))
print(d['age'])
print(type(d['age']))
print(d.shape[0])
# tham chieu
print(d[0])
print(d['age'][0])
d['age'][1]=100
print(d['age'])

[(10,) (20,) (30,)]
<class 'numpy.ndarray'>
[10 20 30]
<class 'numpy.ndarray'>
3
(10,)
10
[ 10 100  30]
